### ISSUE TITLE
freportn does not convert (line 93)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#22]
Could not place object 'RUG4'
Could not place object 'RUG4'
Could not place object 'FRELANT'
Could not place object 'BOAT'
fragtypes: ['21', '22', '03', '04', '05', '08', '09', '2a', '30', '31', '14', '35', '36', '29', '16', '1b', '1c', '15']
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 54, in main
    convertOld(name)
  File "converter.py", line 30, in convertOld
    Wld(zfiles['%s.wld' % name], zfiles).convertZone(zone)
  File "D:\code\eqemu\openeq\converter\wld.py", line 93, in convertZone
    texnames = [x[0] for x in mtex]
TypeError: 'NoneType' object is not iterable

**Comment by xackery** [comment]
similar to #20, not fixed but will close since it's likely same error. Referencing.

**Comment by daeken** [comment]
This is now failing with a different error.  Reopened.
