### ISSUE TITLE
modelviewer doesn't have the json files (bat.json orc.json)

### ISSUE THREAD

**Issue by jjrh** [daeken/OpenEQ#53]
Been trying to figure out how to generate these files - the converter code doesn't write json anywhere. 

```
OpenEQ/ (master✗) $ grep -rin json *  
converter/modelviewer/modelviewer.js:113:        $.ajax(name + '.json').done(function(data) {
```

Am I missing something here or was a file perhaps not committed?

**Comment by daeken** [comment]
The conversion code for this isn't there anymore -- it was mainly just for my own testing.  This is being replaced in the new version by a Xenko scene to view models.  Going to remove the old code as we integrate a brand new conversion pipeline.

**Comment by jjrh** [comment]
Cody Brocious writes:

> The conversion code for this isn't there anymore -- it was mainly just for my
> own testing. This is being replaced in the new version by a Xenko scene to view
> models. Going to remove the old code as we integrate a brand new conversion
> pipeline.

Any way I could get a copy of this older code? (or reference
documentation on the format - google hasn't turned up much)

Been trying to figure out how to extract the EQ character models to
render in webgl and this was the closest I found.

Thanks.

**Comment by jjrh** [comment]
Nevermind the last message - I found the git commit with the code.
