### ISSUE TITLE
README request

### ISSUE THREAD

**Issue by scriptandcompile** [daeken/OpenEQ#60]
I've been trying to fiddle with this for the last few days and I can't figure out any of the esoterics of getting this to work.

So I need to run the ConverterApp to convert the eq files into some other data format? (why? ok, whatever) but what is the magical commands to get it to work? Then where do these files need to live in order to get the client to work? etc etc etc.

A basic 'going from clone to running' readme would make it a *lot* easier to get someone else up and running.

**Comment by daeken** [comment]
Currently we don't really want random folks setting this up, since it's so crazy early stage.  So the readme not being there is a known issue, but kind of intended right now.  If you'd like to get it set up, please ask in the #open-eq channel on the EQEmulator discord.

**Comment by Akkadius** [comment]
Addtheice has actually done a lot of work to the EQEmu base, if he joined our discord and hit up the #open-eq channel I’m sure he could get some instructions :)

**Comment by scriptandcompile** [comment]
ha! I actually only did a little work...it just spread like an evil virus across the whole code base! =P

I'm currently doing a lot of my work in rust, I just wanted to fiddle with this and see what was going on, just play like.

I've almost finished working on an s3d library in rust. =-P

**Comment by Akkadius** [comment]
@addtheice hope you've been well!
